
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec 12 2025 12:27:00 IST (Dec 12 2025 06:57:00 UTC)

// Verification Directory fv/lfsr8 

module lfsr8(clk, rst, lfsr_out);
  input clk, rst;
  output [7:0] lfsr_out;
  wire clk, rst;
  wire [7:0] lfsr_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  DFFQX1 \lfsr_out_reg[0] (.CK (clk), .D (n_8), .Q (lfsr_out[0]));
  NOR2XL g18__2398(.A (n_7), .B (rst), .Y (n_8));
  XNOR2XL g19__5107(.A (lfsr_out[7]), .B (lfsr_out[6]), .Y (n_7));
  DFFQX1 \lfsr_out_reg[7] (.CK (clk), .D (n_6), .Q (lfsr_out[7]));
  OR2X1 g21__6260(.A (lfsr_out[6]), .B (rst), .Y (n_6));
  DFFQX1 \lfsr_out_reg[6] (.CK (clk), .D (n_5), .Q (lfsr_out[6]));
  OR2X1 g23__4319(.A (lfsr_out[5]), .B (rst), .Y (n_5));
  DFFQX1 \lfsr_out_reg[5] (.CK (clk), .D (n_4), .Q (lfsr_out[5]));
  NOR2BX1 g25__8428(.AN (lfsr_out[4]), .B (rst), .Y (n_4));
  DFFQX1 \lfsr_out_reg[4] (.CK (clk), .D (n_3), .Q (lfsr_out[4]));
  NOR2BX1 g27__5526(.AN (lfsr_out[3]), .B (rst), .Y (n_3));
  DFFQX1 \lfsr_out_reg[3] (.CK (clk), .D (n_2), .Q (lfsr_out[3]));
  OR2X1 g29__6783(.A (lfsr_out[2]), .B (rst), .Y (n_2));
  DFFQX1 \lfsr_out_reg[2] (.CK (clk), .D (n_1), .Q (lfsr_out[2]));
  OR2X1 g31__3680(.A (lfsr_out[1]), .B (rst), .Y (n_1));
  DFFQX1 \lfsr_out_reg[1] (.CK (clk), .D (n_0), .Q (lfsr_out[1]));
  NOR2BX1 g33__1617(.AN (lfsr_out[0]), .B (rst), .Y (n_0));
endmodule

